apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubelet-pod-checkpointer-psp
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-checkpointer-psp
subjects:
- kind: Group
  name: system:nodes
  apiGroup: rbac.authorization.k8s.io
