apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: default-ipv4-ippool
spec:
  blockSize: 24
  cidr: {{ .Values.calico.podCIDR }}
  {{ .Values.calico.networkEncapsulation }}: Always
  natOutgoing: true
  nodeSelector: all()
