apiVersion: v1
kind: Secret
metadata:
  name: kube-apiserver
  namespace: kube-system
type: Opaque
data:
  apiserver.key: "{{ .Values.apiserver.apiserverKey }}"
  apiserver.crt: "{{ .Values.apiserver.apiserverCert }}"
  service-account.pub: "{{ .Values.apiserver.serviceAccountPub }}"
  ca.crt: "{{ .Values.apiserver.caCert }}"
  etcd-client-ca.crt: "{{ .Values.apiserver.etcdClientCaCert }}"
  etcd-client.crt: "{{ .Values.apiserver.etcdClientCert }}"
  etcd-client.key: "{{ .Values.apiserver.etcdClientKey }}"
  aggregation-ca.crt: "{{ .Values.apiserver.aggregationCaCert }}"
  aggregation-client.crt: "{{ .Values.apiserver.aggregationClientCert }}"
  aggregation-client.key: "{{ .Values.apiserver.aggregationClientKey }}"